oSearchData = {
"introducción":  [ ["Introduction1.html","Inicio",1] ] ,
"centro":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",8] , ["Whatsnew1.html","Uso de la ventana Portero",5] , ["Introduction1.html","Inicio",1] ] ,
"ayuda":  [ ["Introduction1.html","Inicio",2] ] ,
"este":  [ ["Welcome1.html","Informacion del Software",2] , ["Introduction1.html","Inicio",1] ] ,
"documento":  [ ["Introduction1.html","Inicio",1] ] ,
"familiarizarse":  [ ["Introduction1.html","Inicio",1] ] ,
"rapidamente":  [ ["Introduction1.html","Inicio",1] ] ,
"con":  [ ["Whatsnew1.html","Uso de la ventana Portero",6] , ["Systemrequirements1.html","Uso de la ventana Administrador",4] , ["Introduction1.html","Inicio",1] ] ,
"producto":  [ ["Welcome1.html","Informacion del Software",4] , ["Introduction1.html","Inicio",2] ] ,
"indigo":  [ ["Welcome1.html","Informacion del Software",3] , ["Introduction1.html","Inicio",2] , ["Whatsnew1.html","Uso de la ventana Portero",1] , ["Systemrequirements1.html","Uso de la ventana Administrador",1] , ["GettingStarted1.html","Uso de las ventanas",1] ] ,
"events":  [ ["Welcome1.html","Informacion del Software",3] , ["Introduction1.html","Inicio",2] , ["Whatsnew1.html","Uso de la ventana Portero",1] , ["Systemrequirements1.html","Uso de la ventana Administrador",1] , ["GettingStarted1.html","Uso de las ventanas",1] ] ,
"ofrece":  [ ["Welcome1.html","Informacion del Software",1] , ["Introduction1.html","Inicio",1] ] ,
"informacion":  [ ["Welcome1.html","Informacion del Software",2] , ["Introduction1.html","Inicio",2] ] ,
"general":  [ ["Introduction1.html","Inicio",1] ] ,
"los":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",24] , ["Whatsnew1.html","Uso de la ventana Portero",23] , ["Introduction1.html","Inicio",1] ] ,
"diferentes":  [ ["Whatsnew1.html","Uso de la ventana Portero",4] , ["Systemrequirements1.html","Uso de la ventana Administrador",4] , ["Introduction1.html","Inicio",1] ] ,
"componentes":  [ ["Introduction1.html","Inicio",1] ] ,
"software":  [ ["Welcome1.html","Informacion del Software",2] , ["Introduction1.html","Inicio",2] ] ,
"asi":  [ ["Introduction1.html","Inicio",1] ] ,
"como":  [ ["Introduction1.html","Inicio",1] ] ,
"sus":  [ ["Introduction1.html","Inicio",1] ] ,
"metodos":  [ ["Introduction1.html","Inicio",1] ] ,
"funcionamiento":  [ ["Introduction1.html","Inicio",1] ] ,
"opcione":  [ ["Introduction1.html","Inicio",1] ] ,
"configuracion":  [ ["Introduction1.html","Inicio",1] ] ,
"documentacion":  [ ["Introduction1.html","Inicio",1] ] ,
"consta":  [ ["Introduction1.html","Inicio",1] ] ,
"las":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",9] , ["Whatsnew1.html","Uso de la ventana Portero",7] , ["Introduction1.html","Inicio",1] ] ,
"siguientes":  [ ["Introduction1.html","Inicio",1] ] ,
"secciones":  [ ["Introduction1.html","Inicio",1] ] ,
"uso":  [ ["Welcome1.html","Informacion del Software",1] , ["Introduction1.html","Inicio",1] ] ,
"copyright":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",1] , ["Whatsnew1.html","Uso de la ventana Portero",1] , ["GettingStarted1.html","Uso de las ventanas",1] , ["Introduction1.html","Inicio",1] , ["Welcome1.html","Informacion del Software",1] ] ,
"2012":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",1] , ["Whatsnew1.html","Uso de la ventana Portero",1] , ["GettingStarted1.html","Uso de las ventanas",1] , ["Introduction1.html","Inicio",1] , ["Welcome1.html","Informacion del Software",1] ] ,
"created":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",1] , ["Whatsnew1.html","Uso de la ventana Portero",1] , ["GettingStarted1.html","Uso de las ventanas",1] , ["Introduction1.html","Inicio",1] , ["Welcome1.html","Informacion del Software",1] ] ,
"with":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",1] , ["Whatsnew1.html","Uso de la ventana Portero",1] , ["GettingStarted1.html","Uso de las ventanas",1] , ["Introduction1.html","Inicio",1] , ["Welcome1.html","Informacion del Software",1] ] ,
"the":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",1] , ["Whatsnew1.html","Uso de la ventana Portero",1] , ["GettingStarted1.html","Uso de las ventanas",1] , ["Introduction1.html","Inicio",1] , ["Welcome1.html","Informacion del Software",1] ] ,
"freeware":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",1] , ["Whatsnew1.html","Uso de la ventana Portero",1] , ["GettingStarted1.html","Uso de las ventanas",1] , ["Introduction1.html","Inicio",1] , ["Welcome1.html","Informacion del Software",1] ] ,
"edition":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",1] , ["Whatsnew1.html","Uso de la ventana Portero",1] , ["GettingStarted1.html","Uso de las ventanas",1] , ["Introduction1.html","Inicio",1] , ["Welcome1.html","Informacion del Software",1] ] ,
"helpndoc":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",1] , ["Whatsnew1.html","Uso de la ventana Portero",1] , ["GettingStarted1.html","Uso de las ventanas",1] , ["Introduction1.html","Inicio",1] , ["Welcome1.html","Informacion del Software",1] ] ,
"single":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",1] , ["Introduction1.html","Inicio",1] ] ,
"source":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",1] , ["Introduction1.html","Inicio",1] ] ,
"chm":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",1] , ["Introduction1.html","Inicio",1] ] ,
"pdf":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",1] , ["Introduction1.html","Inicio",1] ] ,
"doc":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",1] , ["Introduction1.html","Inicio",1] ] ,
"and":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",1] , ["Introduction1.html","Inicio",1] ] ,
"html":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",1] , ["Introduction1.html","Inicio",1] ] ,
"help":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",1] , ["Whatsnew1.html","Uso de la ventana Portero",1] , ["Introduction1.html","Inicio",1] , ["GettingStarted1.html","Uso de las ventanas",1] ] ,
"creation":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",1] , ["Introduction1.html","Inicio",1] ] ,
"información":  [ ["Welcome1.html","Informacion del Software",1] ] ,
"seccion":  [ ["Welcome1.html","Informacion del Software",1] ] ,
"proporciona":  [ ["Welcome1.html","Informacion del Software",1] ] ,
"toda":  [ ["Welcome1.html","Informacion del Software",1] ] ,
"relevante":  [ ["Welcome1.html","Informacion del Software",1] ] ,
"para":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",4] , ["Welcome1.html","Informacion del Software",3] , ["Whatsnew1.html","Uso de la ventana Portero",1] ] ,
"adquisicion":  [ ["Welcome1.html","Informacion del Software",1] ] ,
"herramientas":  [ ["Welcome1.html","Informacion del Software",1] ] ,
"completas":  [ ["Welcome1.html","Informacion del Software",1] ] ,
"flexibles":  [ ["Welcome1.html","Informacion del Software",1] ] ,
"manejar":  [ ["Welcome1.html","Informacion del Software",2] ] ,
"eventos":  [ ["Whatsnew1.html","Uso de la ventana Portero",15] , ["Systemrequirements1.html","Uso de la ventana Administrador",4] , ["Welcome1.html","Informacion del Software",1] ] ,
"facil":  [ ["Welcome1.html","Informacion del Software",1] ] ,
"utilidad":  [ ["Welcome1.html","Informacion del Software",1] ] ,
"que":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",14] , ["Whatsnew1.html","Uso de la ventana Portero",9] , ["Welcome1.html","Informacion del Software",1] ] ,
"permite":  [ ["Welcome1.html","Informacion del Software",1] ] ,
"usuario":  [ ["Whatsnew1.html","Uso de la ventana Portero",3] , ["Systemrequirements1.html","Uso de la ventana Administrador",3] , ["Welcome1.html","Informacion del Software",1] ] ,
"facilidad":  [ ["Welcome1.html","Informacion del Software",1] ] ,
"poder":  [ ["Welcome1.html","Informacion del Software",1] ] ,
"utlizar":  [ ["Welcome1.html","Informacion del Software",1] ] ,
"necesita":  [ ["Welcome1.html","Informacion del Software",1] ] ,
"una":  [ ["Whatsnew1.html","Uso de la ventana Portero",2] , ["Welcome1.html","Informacion del Software",1] ] ,
"licencia":  [ ["Welcome1.html","Informacion del Software",3] ] ,
"emite":  [ ["Welcome1.html","Informacion del Software",1] ] ,
"travez":  [ ["Welcome1.html","Informacion del Software",1] ] ,
"compra":  [ ["Welcome1.html","Informacion del Software",1] ] ,
"numero":  [ ["Welcome1.html","Informacion del Software",1] ] ,
"esta":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",8] , ["Whatsnew1.html","Uso de la ventana Portero",5] , ["Welcome1.html","Informacion del Software",1] ] ,
"debajo":  [ ["Welcome1.html","Informacion del Software",1] ] ,
"caratula":  [ ["Welcome1.html","Informacion del Software",1] ] ,
"del":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",12] , ["Whatsnew1.html","Uso de la ventana Portero",6] , ["Welcome1.html","Informacion del Software",1] ] ,
"full":  [ ["Welcome1.html","Informacion del Software",1] ] ,
"featured":  [ ["Welcome1.html","Informacion del Software",1] ] ,
"documentation":  [ ["Welcome1.html","Informacion del Software",1] ] ,
"generator":  [ ["Welcome1.html","Informacion del Software",1] ] ,
"usos":  [ ["GettingStarted1.html","Uso de las ventanas",1] ] ,
"easily":  [ ["Whatsnew1.html","Uso de la ventana Portero",1] , ["GettingStarted1.html","Uso de las ventanas",1] ] ,
"create":  [ ["Whatsnew1.html","Uso de la ventana Portero",1] , ["GettingStarted1.html","Uso de las ventanas",1] ] ,
"documents":  [ ["Whatsnew1.html","Uso de la ventana Portero",1] , ["GettingStarted1.html","Uso de las ventanas",1] ] ,
"ventana":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",7] , ["Whatsnew1.html","Uso de la ventana Portero",5] ] ,
"administrador":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",8] ] ,
"mantenimiento":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",8] ] ,
"divide":  [ ["Whatsnew1.html","Uso de la ventana Portero",4] , ["Systemrequirements1.html","Uso de la ventana Administrador",4] ] ,
"tres":  [ ["Whatsnew1.html","Uso de la ventana Portero",4] , ["Systemrequirements1.html","Uso de la ventana Administrador",4] ] ,
"partes":  [ ["Whatsnew1.html","Uso de la ventana Portero",4] , ["Systemrequirements1.html","Uso de la ventana Administrador",4] ] ,
"lado":  [ ["Whatsnew1.html","Uso de la ventana Portero",4] , ["Systemrequirements1.html","Uso de la ventana Administrador",4] ] ,
"izquiedo":  [ ["Whatsnew1.html","Uso de la ventana Portero",4] , ["Systemrequirements1.html","Uso de la ventana Administrador",4] ] ,
"estan":  [ ["Whatsnew1.html","Uso de la ventana Portero",8] , ["Systemrequirements1.html","Uso de la ventana Administrador",4] ] ,
"menus":  [ ["Whatsnew1.html","Uso de la ventana Portero",8] , ["Systemrequirements1.html","Uso de la ventana Administrador",8] ] ,
"parte":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",12] , ["Whatsnew1.html","Uso de la ventana Portero",7] ] ,
"tabla":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",4] ] ,
"registro":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",12] , ["Whatsnew1.html","Uso de la ventana Portero",4] ] ,
"arriba":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",4] , ["Whatsnew1.html","Uso de la ventana Portero",2] ] ,
"opciones":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",4] , ["Whatsnew1.html","Uso de la ventana Portero",2] ] ,
"manipularan":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",4] ] ,
"registros":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",8] , ["Whatsnew1.html","Uso de la ventana Portero",5] ] ,
"barra":  [ ["Whatsnew1.html","Uso de la ventana Portero",5] , ["Systemrequirements1.html","Uso de la ventana Administrador",4] ] ,
"menu":  [ ["Whatsnew1.html","Uso de la ventana Portero",4] , ["Systemrequirements1.html","Uso de la ventana Administrador",4] ] ,
"puede":  [ ["Whatsnew1.html","Uso de la ventana Portero",4] , ["Systemrequirements1.html","Uso de la ventana Administrador",4] ] ,
"selecionar":  [ ["Whatsnew1.html","Uso de la ventana Portero",4] , ["Systemrequirements1.html","Uso de la ventana Administrador",4] ] ,
"ventanas":  [ ["Whatsnew1.html","Uso de la ventana Portero",4] , ["Systemrequirements1.html","Uso de la ventana Administrador",4] ] ,
"quiere":  [ ["Whatsnew1.html","Uso de la ventana Portero",4] , ["Systemrequirements1.html","Uso de la ventana Administrador",4] ] ,
"trabajar":  [ ["Whatsnew1.html","Uso de la ventana Portero",4] , ["Systemrequirements1.html","Uso de la ventana Administrador",4] ] ,
"tablas":  [ ["Whatsnew1.html","Uso de la ventana Portero",4] , ["Systemrequirements1.html","Uso de la ventana Administrador",4] ] ,
"area":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",4] , ["Whatsnew1.html","Uso de la ventana Portero",2] ] ,
"localizan":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",4] , ["Whatsnew1.html","Uso de la ventana Portero",2] ] ,
"ingresados":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",4] , ["Whatsnew1.html","Uso de la ventana Portero",2] ] ,
"por":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",4] , ["Whatsnew1.html","Uso de la ventana Portero",2] ] ,
"ingreso":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",4] , ["Whatsnew1.html","Uso de la ventana Portero",1] ] ,
"utiliza":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",4] , ["Whatsnew1.html","Uso de la ventana Portero",1] ] ,
"manipular":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",4] ] ,
"usuarios":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",2] ] ,
"ingresen":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",4] ] ,
"invitados":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",8] , ["Whatsnew1.html","Uso de la ventana Portero",1] ] ,
"invitaciones":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",2] ] ,
"invitadosse":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",1] ] ,
"son":  [ ["Systemrequirements1.html","Uso de la ventana Administrador",2] , ["Whatsnew1.html","Uso de la ventana Portero",1] ] ,
"portero":  [ ["Whatsnew1.html","Uso de la ventana Portero",5] ] ,
"dia":  [ ["Whatsnew1.html","Uso de la ventana Portero",3] ] ,
"listado":  [ ["Whatsnew1.html","Uso de la ventana Portero",1] ] ,
"derecha":  [ ["Whatsnew1.html","Uso de la ventana Portero",4] ] ,
"trabajaran":  [ ["Whatsnew1.html","Uso de la ventana Portero",2] ] ,
"evento":  [ ["Whatsnew1.html","Uso de la ventana Portero",4] ] ,
"selecciona":  [ ["Whatsnew1.html","Uso de la ventana Portero",1] ] ,
"lista":  [ ["Whatsnew1.html","Uso de la ventana Portero",5] ] ,
"despues":  [ ["Whatsnew1.html","Uso de la ventana Portero",2] ] ,
"iniciar":  [ ["Whatsnew1.html","Uso de la ventana Portero",2] ] ,
"secion":  [ ["Whatsnew1.html","Uso de la ventana Portero",2] ] ,
"automaticamente":  [ ["Whatsnew1.html","Uso de la ventana Portero",5] ] ,
"saldra":  [ ["Whatsnew1.html","Uso de la ventana Portero",4] ] ,
"seleccion":  [ ["Whatsnew1.html","Uso de la ventana Portero",4] ] ,
"cuando":  [ ["Whatsnew1.html","Uso de la ventana Portero",2] ] ,
"eliges":  [ ["Whatsnew1.html","Uso de la ventana Portero",2] ] ,
"datos":  [ ["Whatsnew1.html","Uso de la ventana Portero",2] ] ,
"correspondientes":  [ ["Whatsnew1.html","Uso de la ventana Portero",2] ] ,
"busca":  [ ["Whatsnew1.html","Uso de la ventana Portero",1] ] ,
"busqueda":  [ ["Whatsnew1.html","Uso de la ventana Portero",2] ] ,
"aparecen":  [ ["Whatsnew1.html","Uso de la ventana Portero",3] ] ,
"opcion":  [ ["Whatsnew1.html","Uso de la ventana Portero",2] ] ,
"buscar":  [ ["Whatsnew1.html","Uso de la ventana Portero",2] ] ,
"ingresa":  [ ["Whatsnew1.html","Uso de la ventana Portero",1] ] ,
"desea":  [ ["Whatsnew1.html","Uso de la ventana Portero",1] ] ,
"proximos":  [ ["Whatsnew1.html","Uso de la ventana Portero",5] ] ,
"seleccionado":  [ ["Whatsnew1.html","Uso de la ventana Portero",1] ] ,
"visitas":  [ ["Whatsnew1.html","Uso de la ventana Portero",3] ] ,
"imprevistas":  [ ["Whatsnew1.html","Uso de la ventana Portero",3] ] ,
"ingresar":  [ ["Whatsnew1.html","Uso de la ventana Portero",2] ] ,
"registra":  [ ["Whatsnew1.html","Uso de la ventana Portero",1] ] ,
"mas":  [ ["Whatsnew1.html","Uso de la ventana Portero",1] ] ,
"abajo":  [ ["Whatsnew1.html","Uso de la ventana Portero",1] ]
}